/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Inter"', "system-ui", "sans-serif"],
        sans: ['"Inter"', "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        "2xs": ["0.625rem", { lineHeight: "0.875rem" }],
      },
      spacing: {
        18: "4.5rem",
        22: "5.5rem",
        30: "7.5rem",
      },
      borderRadius: {
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
      colors: {
        bone: "#F5F5F7",
        ash: "#FAFAFA",
        card: "#FFFFFF",
        line: "#E5E5E7",
        ink: "#1D1D1F",
        accent: {
          DEFAULT: "#1D1D1F",
          hover: "#000000",
          soft: "#F5F5F7",
        },
        success: { DEFAULT: "#30D158", soft: "#E8F8ED" },
        warning: { DEFAULT: "#FF9F0A", soft: "#FFF3E0" },
        danger: { DEFAULT: "#FF453A", soft: "#FFE8E6" },
        surface: "#FFFFFF",
        surfacehover: "#F5F5F7",
        sanguine: { DEFAULT: "#1D1D1F", hover: "#000000", soft: "#F5F5F7" },
        neutral: {
          50: "#F9F9FB",
          100: "#F5F5F7",
          200: "#E5E5E7",
          300: "#D2D2D7",
          400: "#A1A1A6",
          500: "#8E8E93",
          600: "#6E6E73",
          700: "#48484A",
          800: "#363638",
          900: "#1D1D1F",
          950: "#0D0D0F",
        },
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.02)",
        "card-hover": "0 4px 12px rgba(0,0,0,0.06), 0 2px 4px rgba(0,0,0,0.03)",
        "card-lg": "0 8px 30px rgba(0,0,0,0.06), 0 2px 8px rgba(0,0,0,0.03)",
        nav: "0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.02)",
        modal: "0 20px 60px rgba(0,0,0,0.08), 0 4px 16px rgba(0,0,0,0.04)",
        float: "0 4px 20px rgba(0,0,0,0.06)",
      },
      keyframes: {
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "fade-up": { "0%": { opacity: "0", transform: "translateY(12px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-down": { "0%": { opacity: "0", transform: "translateY(-8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { "0%": { opacity: "0", transform: "scale(0.95)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        "slide-left": { "0%": { transform: "translateX(100%)" }, "100%": { transform: "translateX(0)" } },
        "slide-right": { "0%": { transform: "translateX(-100%)" }, "100%": { transform: "translateX(0)" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "card-lift": { "0%": { transform: "translateY(0)", boxShadow: "0 1px 3px rgba(0,0,0,0.04)" }, "100%": { transform: "translateY(-2px)", boxShadow: "0 4px 12px rgba(0,0,0,0.06)" } },
        "spin-slow": { "0%": { transform: "rotate(0deg)" }, "100%": { transform: "rotate(360deg)" } },
        "pulse-soft": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.5" } },
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      animation: {
        "fade-in": "fade-in 0.3s ease-out both",
        "fade-up": "fade-up 0.4s ease-out both",
        "fade-down": "fade-down 0.3s ease-out both",
        "scale-in": "scale-in 0.2s ease-out both",
        "slide-left": "slide-left 0.3s ease-out both",
        "slide-right": "slide-right 0.3s ease-out both",
        shimmer: "shimmer 1.8s ease-in-out infinite",
        "card-lift": "card-lift 0.25s ease-out forwards",
        "spin-slow": "spin-slow 2s linear infinite",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
