import { useEffect, useMemo, useRef, useState, useCallback } from "react";
import { createRoot } from "react-dom/client";
import { useParams, useNavigate } from "react-router-dom";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { toast } from "sonner";
import {
  Save, Download, ChevronLeft, Loader2, Plus, Trash2, Copy,
  Sparkles, Undo2, Redo2, Wand2, FileText, LayoutGrid, Maximize2, Mountain,
} from "lucide-react";

import { api, isCreditError } from "../lib/api";
import { PageHeader } from "../components/AppLayout";
import { useAuth } from "../lib/auth";
import { PALETTES, CANVAS, blankSlide, slideFromTemplate } from "../lib/creqTemplates";
import { ensureProjectFontsLoaded, waitForProjectFonts } from "../lib/googleFonts";

import LeftPanel from "../components/creq/LeftPanel";
import RightPanel from "../components/creq/RightPanel";
import BoardView from "../components/creq/BoardView";
import ElementRender from "../components/creq/ElementRender";
import SelectionChrome from "../components/creq/SelectionChrome";
import PanoramaLayer from "../components/creq/PanoramaLayer";
import DeckOverlay from "../components/creq/DeckOverlay";
import BrandKitDrawer from "../components/creq/drawers/BrandKitDrawer";
import AiImageDrawer from "../components/creq/drawers/AiImageDrawer";
import PanoramaDrawer from "../components/creq/drawers/PanoramaDrawer";
import PdfExportDialog, { EXPORT_QUALITIES } from "../components/creq/drawers/PdfExportDialog";
import { newId, renderBackground, stripLocalKeys, elementBounds } from "../components/creq/utils";

/* ------------------------- Project load / hydrate ------------------------- */

/** Convert one backend/LLM-drafted slide `{title,subtitle,body,cta}` into the
 * editor's element-list shape. Shared by hydrate() (loading a project that
 * still has legacy-shape slides) and the in-editor "Generate content" action
 * (appending freshly-generated slides to an already-open deck). */
function legacySlideToElements(s) {
  const els = [];
  if (s.subtitle) els.push({ id: newId(), type: "text", x: 80, y: 120, w: 920, h: 60, text: s.subtitle,
    font: "JetBrains Mono", size: 24, weight: 500, uppercase: true, letter_spacing: 0.2, color: "muted", align: "left" });
  if (s.title) els.push({ id: newId(), type: "text", x: 80, y: 260, w: 920, h: 480, text: s.title,
    font: "Archivo Black", size: 132, weight: 900, color: "accent", line_height: 0.95, align: "left" });
  if (s.body) els.push({ id: newId(), type: "text", x: 80, y: 820, w: 920, h: 380, text: s.body,
    font: "Inter", size: 32, weight: 400, color: "text", line_height: 1.4, align: "left" });
  if (s.cta) els.push({ id: newId(), type: "badge", x: 80, y: 1180, text: s.cta, bg: "accent", color: "bg", radius: 999, size: 22 });
  return { _k: newId(), bg: { type: "solid", color: "bg" }, elements: els };
}

function hydrate(project) {
  const p = { ...project };
  p.palette_id = p.palette_id || "midnight";
  p.slides = (p.slides || []).map((s) => {
    if (s && !s.elements && (s.title || s.body || s.subtitle)) {
      return legacySlideToElements(s);
    }
    return {
      _k: s._k || newId(),
      bg: s.bg || { type: "solid", color: "bg" },
      elements: (s.elements || []).map((e) => ({ ...e, id: e.id || newId() })),
    };
  });
  if (!p.slides.length) p.slides.push(blankSlide());
  p.brand = normalizeBrand(p.brand);
  // Every carousel carries "Made with Innoira Agentic Suite" branding by
  // default — `??` (not `||`) so an explicit `false` a user already saved
  // (they turned it off) stays off, but a field that's simply missing
  // (every carousel created before this existed, or freshly generated by
  // the backend) defaults to on.
  p.show_branding = project.show_branding ?? true;
  return p;
}

/** The editor and the backend's carousel-generate step have historically
 * written two different `brand` shapes — the editor's own
 * `{logo_url, colors, fonts}` (see applyBrandKit below) and the generator's
 * legacy `{bg, accent, text, font, logo_text}`. Normalize to one shape on
 * load so the editor only ever has to read/write a single schema. */
function normalizeBrand(brand) {
  if (!brand) return { logo_url: null, colors: [], fonts: [] };
  if ("colors" in brand || "logo_url" in brand) {
    // Already the editor's shape.
    return { logo_url: brand.logo_url ?? null, colors: brand.colors || [], fonts: brand.fonts || [] };
  }
  // Legacy generator shape — carry over what maps cleanly, drop the rest.
  const colors = [brand.bg, brand.accent, brand.text].filter(Boolean);
  const fonts = brand.font ? [brand.font] : [];
  return { logo_url: null, colors, fonts };
}

/* ------------------------------- Editor ---------------------------------- */

/** Canva/Figma-style smart snapping. Given the element being dragged (its
 * proposed x/y + size) and the other elements on the slide, snap each of the
 * element's 3 vertical edges (left/center/right) and 3 horizontal edges
 * (top/middle/bottom) to the nearest matching edge of another element or of
 * the canvas itself, within a small threshold. Returns the adjusted x/y and
 * the guide lines to draw. */
function computeSnap(dragged, propX, propY, others, threshold = 7) {
  const w = dragged.w || 0, h = dragged.h || 0;
  // Candidate vertical lines (x positions) and horizontal lines (y positions).
  const vTargets = [0, CANVAS.w / 2, CANVAS.w];
  const hTargets = [0, CANVAS.h / 2, CANVAS.h];
  others.forEach((o) => {
    vTargets.push(o.x, o.x + (o.w || 0) / 2, o.x + (o.w || 0));
    hTargets.push(o.y, o.y + (o.h || 0) / 2, o.y + (o.h || 0));
  });

  let x = propX, y = propY;
  const guideLines = [];

  // Vertical snapping — element's left, center, right against each x target.
  const vEdges = [propX, propX + w / 2, propX + w];
  let bestV = null;
  vTargets.forEach((t) => {
    vEdges.forEach((edge, ei) => {
      const d = Math.abs(edge - t);
      if (d <= threshold && (!bestV || d < bestV.d)) bestV = { d, t, ei };
    });
  });
  if (bestV) {
    x = propX + (bestV.t - vEdges[bestV.ei]);
    guideLines.push({ o: "v", pos: bestV.t });
  }

  // Horizontal snapping — element's top, middle, bottom against each y target.
  const hEdges = [propY, propY + h / 2, propY + h];
  let bestH = null;
  hTargets.forEach((t) => {
    hEdges.forEach((edge, ei) => {
      const d = Math.abs(edge - t);
      if (d <= threshold && (!bestH || d < bestH.d)) bestH = { d, t, ei };
    });
  });
  if (bestH) {
    y = propY + (bestH.t - hEdges[bestH.ei]);
    guideLines.push({ o: "h", pos: bestH.t });
  }

  return { x: Math.round(x), y: Math.round(y), guides: guideLines };
}

export default function CreateEQEditor() {
  const { id } = useParams();
  const nav = useNavigate();
  const { user } = useAuth();
  const [proj, setProj] = useState(null);
  const [activeSlide, setActiveSlide] = useState(0);
  const [selectedId, setSelectedId] = useState(null);
  const [selectedIds, setSelectedIds] = useState(() => new Set());
  const [marqueeRect, setMarqueeRect] = useState(null);
  const [guides, setGuides] = useState([]); // smart-snap alignment lines during drag
  const marqueeState = useRef(null);
  const selectSingle = useCallback((id) => {
    setSelectedId(id);
    setSelectedIds(id ? new Set([id]) : new Set());
  }, []);
  const [busy, setBusy] = useState(false);
  const [zoom, setZoom] = useState(0.38);
  const [brandKits, setBrandKits] = useState([]);
  const [showBrandKit, setShowBrandKit] = useState(false);
  const [showAiImage, setShowAiImage] = useState(false);
  const [showPanorama, setShowPanorama] = useState(false);
  const [showPdfPicker, setShowPdfPicker] = useState(false);
  const [showGenerateContent, setShowGenerateContent] = useState(false);
  const [viewMode, setViewMode] = useState("focus");
  const [dropHint, setDropHint] = useState(false);
  const canvasRef = useRef(null);
  const dragState = useRef(null);
  const resizeState = useRef(null);
  const rotateState = useRef(null);
  const groupResizeState = useRef(null);
  const panoDragState = useRef(null);
  // Live manipulation readout for the HUD pill in SelectionChrome —
  // { mode: "drag"|"resize"|"rotate", label } while a gesture is in flight.
  const [interaction, setInteraction] = useState(null);
  // Badges auto-size to their text, so the chrome can't trust their stored
  // w/h — ElementRender reports real rendered bounds here (canvas px).
  // Kept in a ref (the map identity changes rarely) with a tick to re-render
  // the chrome when a measurement actually moves.
  const measuredRef = useRef({});
  const [, setMeasureTick] = useState(0);
  const historyRef = useRef({ past: [], future: [] });
  const clipboardRef = useRef(null); // { el } — copied element for paste
  const imageFileRef = useRef(null);
  // Always-current project snapshot, so gesture helpers can read state without
  // being re-created (and re-subscribing) on every render.
  const projRef = useRef(null);
  // A "gesture" is one continuous burst of edits (a drag, a resize, a slider
  // sweep). We push a single history snapshot at its start, then update state
  // live without re-serialising the whole project on every frame.
  const gestureActive = useRef(false);
  const endGestureTimer = useRef(null);

  useEffect(() => {
    api.get(`/carousel/${id}`).then((r) => {
      const hydrated = hydrate(r.data);
      setProj(hydrated);
      // A saved deck can reference any of the ~1900 Google Fonts, not just the
      // 10 preloaded in index.html — without this, reopening a project would
      // silently render text in the browser's fallback font until each text
      // element happened to be selected (which re-triggers the picker's load).
      ensureProjectFontsLoaded(hydrated.slides);
    });
    api.get("/brandkits").then((r) => setBrandKits(r.data)).catch(() => {});
  }, [id]);

  useEffect(() => { projRef.current = proj; }, [proj]);

  // Refs mirroring hot state, so pointer handlers can be created ONCE instead
  // of on every zoom/selection/slide change — without this, every selection
  // click re-renders all memo'd ElementRenders through new callback props.
  const zoomRef = useRef(zoom);
  const activeSlideRef = useRef(activeSlide);
  const selectedIdsRef = useRef(selectedIds);
  useEffect(() => { zoomRef.current = zoom; }, [zoom]);
  useEffect(() => { activeSlideRef.current = activeSlide; }, [activeSlide]);
  useEffect(() => { selectedIdsRef.current = selectedIds; }, [selectedIds]);

  const onElementMeasure = useCallback((elId, size) => {
    const cur = measuredRef.current[elId];
    if (cur && Math.abs(cur.w - size.w) < 0.5 && Math.abs(cur.h - size.h) < 0.5) return;
    measuredRef.current = { ...measuredRef.current, [elId]: size };
    setMeasureTick((t) => t + 1);
  }, []);

  const palette = useMemo(
    () => PALETTES.find((p) => p.id === proj?.palette_id) || PALETTES[0],
    [proj?.palette_id]
  );

  const slide = proj?.slides?.[activeSlide];
  const selected = slide?.elements?.find((e) => e.id === selectedId);

  /* --- History (undo/redo) --- */
  const pushHistory = useCallback((snapshot) => {
    historyRef.current.past.push(snapshot);
    if (historyRef.current.past.length > 50) historyRef.current.past.shift();
    historyRef.current.future = [];
  }, []);
  const undo = useCallback(() => {
    const h = historyRef.current;
    if (!h.past.length) return;
    setProj((cur) => {
      if (!cur) return cur;
      h.future.push(JSON.stringify(cur));
      return JSON.parse(h.past.pop());
    });
  }, []);
  const redo = useCallback(() => {
    const h = historyRef.current;
    if (!h.future.length) return;
    setProj((cur) => {
      if (!cur) return cur;
      h.past.push(JSON.stringify(cur));
      return JSON.parse(h.future.pop());
    });
  }, []);
  const mutate = useCallback((updater) => {
    setProj((cur) => {
      if (!cur) return cur;
      pushHistory(JSON.stringify(cur));
      const next = { ...cur, slides: cur.slides.map((s) => ({ ...s, elements: [...(s.elements || [])] })) };
      updater(next);
      return next;
    });
  }, [pushHistory]);

  /** Same shape as mutate(), but never serialises the project — for use
   * inside an active gesture (drag/resize/slider-sweep/typing) where history
   * was already captured once by beginGesture(). */
  const mutateLive = useCallback((updater) => {
    setProj((cur) => {
      if (!cur) return cur;
      const next = { ...cur, slides: cur.slides.map((s) => ({ ...s, elements: [...(s.elements || [])] })) };
      updater(next);
      return next;
    });
  }, []);

  /** Call at the start of a continuous interaction (pointerdown, focus,
   * mousedown on a slider) to push exactly one history snapshot for the
   * whole gesture. Safe to call repeatedly — only the first call in a
   * gesture actually pushes. Includes a self-healing timeout in case the
   * matching endGesture() is missed (e.g. picking an option from a native
   * <select> popup never fires a pointerup our container can see) — without
   * it, a missed end would leave every future edit silently skipping history
   * until some unrelated pointer event happened to reset it. */
  const beginGesture = useCallback(() => {
    if (endGestureTimer.current) clearTimeout(endGestureTimer.current);
    endGestureTimer.current = setTimeout(() => { gestureActive.current = false; }, 1500);
    if (gestureActive.current) return;
    gestureActive.current = true;
    if (projRef.current) pushHistory(JSON.stringify(projRef.current));
  }, [pushHistory]);

  /** Call at the end of a continuous interaction (pointerup, blur). */
  const endGesture = useCallback(() => {
    gestureActive.current = false;
    if (endGestureTimer.current) { clearTimeout(endGestureTimer.current); endGestureTimer.current = null; }
  }, []);

  /* --- Slide / element mutations --- */
  const patchSlide = useCallback((patch) => mutate((n) => Object.assign(n.slides[activeSlide], patch)), [mutate, activeSlide]);
  const patchElement = useCallback((elId, patch) => {
    const m = gestureActive.current ? mutateLive : mutate;
    m((n) => {
      const s = n.slides[activeSlide];
      s.elements = s.elements.map((e) => (e.id === elId ? { ...e, ...patch } : e));
    });
  }, [mutate, mutateLive, activeSlide]);
  const addElement = (el) => {
    const withId = { ...el, id: newId() };
    mutate((n) => n.slides[activeSlide].elements.push(withId));
    selectSingle(withId.id);
  };
  const deleteElement = (elId) => {
    mutate((n) => { n.slides[activeSlide].elements = n.slides[activeSlide].elements.filter((e) => e.id !== elId); });
    selectSingle(null);
  };
  const deleteSelectedElements = () => {
    if (selectedIds.size <= 1) { deleteElement(selectedId); return; }
    mutate((n) => { n.slides[activeSlide].elements = n.slides[activeSlide].elements.filter((e) => !selectedIds.has(e.id)); });
    selectSingle(null);
  };
  /** Nudge every selected element by (dx, dy) canvas px — arrow keys. */
  const nudgeSelected = (dx, dy) => {
    if (!selectedIds.size) return;
    mutate((n) => {
      n.slides[activeSlide].elements = n.slides[activeSlide].elements.map((e) =>
        selectedIds.has(e.id) ? { ...e, x: Math.round((e.x || 0) + dx), y: Math.round((e.y || 0) + dy) } : e);
    });
  };
  /** Align / distribute the selected elements against their common bounding
   * box (Canva-style). With a single element selected, "center"/"middle" align
   * it to the canvas instead, which is the more useful behaviour there. */
  const alignSelected = (mode) => {
    const els = slide.elements.filter((e) => selectedIds.has(e.id));
    if (!els.length) return;
    const single = els.length === 1;
    const minX = Math.min(...els.map((e) => e.x));
    const maxX = Math.max(...els.map((e) => e.x + (e.w || 0)));
    const minY = Math.min(...els.map((e) => e.y));
    const maxY = Math.max(...els.map((e) => e.y + (e.h || 0)));
    const cX = single ? CANVAS.w / 2 : (minX + maxX) / 2;
    const cY = single ? CANVAS.h / 2 : (minY + maxY) / 2;
    const patch = {};
    if (mode === "left") els.forEach((e) => { patch[e.id] = { x: Math.round(minX) }; });
    if (mode === "right") els.forEach((e) => { patch[e.id] = { x: Math.round(maxX - (e.w || 0)) }; });
    if (mode === "hcenter") els.forEach((e) => { patch[e.id] = { x: Math.round(cX - (e.w || 0) / 2) }; });
    if (mode === "top") els.forEach((e) => { patch[e.id] = { y: Math.round(minY) }; });
    if (mode === "bottom") els.forEach((e) => { patch[e.id] = { y: Math.round(maxY - (e.h || 0)) }; });
    if (mode === "vcenter") els.forEach((e) => { patch[e.id] = { y: Math.round(cY - (e.h || 0) / 2) }; });
    if (mode === "dist-h" && els.length > 2) {
      const sorted = [...els].sort((a, b) => a.x - b.x);
      const span = (sorted[sorted.length - 1].x) - sorted[0].x;
      const step = span / (sorted.length - 1);
      sorted.forEach((e, i) => { patch[e.id] = { x: Math.round(sorted[0].x + step * i) }; });
    }
    if (mode === "dist-v" && els.length > 2) {
      const sorted = [...els].sort((a, b) => a.y - b.y);
      const span = (sorted[sorted.length - 1].y) - sorted[0].y;
      const step = span / (sorted.length - 1);
      sorted.forEach((e, i) => { patch[e.id] = { y: Math.round(sorted[0].y + step * i) }; });
    }
    mutate((n) => {
      n.slides[activeSlide].elements = n.slides[activeSlide].elements.map((e) =>
        patch[e.id] ? { ...e, ...patch[e.id] } : e);
    });
  };
  const duplicateElement = (elId) => {
    const src = slide.elements.find((e) => e.id === elId);
    if (!src) return;
    const copy = { ...src, id: newId(), x: (src.x || 0) + 40, y: (src.y || 0) + 40 };
    mutate((n) => n.slides[activeSlide].elements.push(copy));
    selectSingle(copy.id);
  };
  const bringToFront = (elId) => mutate((n) => {
    const s = n.slides[activeSlide];
    const idx = s.elements.findIndex((e) => e.id === elId);
    if (idx > -1) { const [el] = s.elements.splice(idx, 1); s.elements.push(el); }
  });
  const sendToBack = (elId) => mutate((n) => {
    const s = n.slides[activeSlide];
    const idx = s.elements.findIndex((e) => e.id === elId);
    if (idx > -1) { const [el] = s.elements.splice(idx, 1); s.elements.unshift(el); }
  });

  /* --- Slides --- */
  const addSlide = () => {
    mutate((n) => { n.slides.push(blankSlide()); });
    setActiveSlide(proj.slides.length);
    selectSingle(null);
  };
  /** Clicking a template in the LeftPanel restyles the currently active
   * slide with that template's layout — it does not add a new slide (that's
   * what the "+ Slide" button is for). */
  const applyTemplateToSlide = (tpl) => {
    const built = slideFromTemplate(tpl);
    mutate((n) => {
      const cur = n.slides[activeSlide];
      n.slides[activeSlide] = { ...built, _k: cur._k };
    });
    selectSingle(null);
  };
  const duplicateSlide = () => {
    const src = slide;
    const copy = { ...src, _k: newId(), elements: src.elements.map((e) => ({ ...e, id: newId() })) };
    mutate((n) => n.slides.splice(activeSlide + 1, 0, copy));
    setActiveSlide(activeSlide + 1);
  };
  const deleteSlide = () => {
    if (proj.slides.length === 1) return;
    mutate((n) => n.slides.splice(activeSlide, 1));
    setActiveSlide(Math.max(0, activeSlide - 1));
    selectSingle(null);
  };

  /* --- Panorama manual controls --- */
  const setPanoViewport = useCallback((vp) => {
    const m = gestureActive.current ? mutateLive : mutate;
    m((n) => {
      n.panorama = n.panorama || {};
      n.panorama.viewports = n.panorama.viewports || [];
      n.panorama.viewports[activeSlide] = { ox: vp.ox ?? 50, oy: vp.oy ?? 50, scale: vp.scale ?? 1 };
    });
  }, [mutate, mutateLive, activeSlide]);
  const resetPanoSlide = () => setPanoViewport({ ox: 50, oy: 50, scale: 1 });
  const applyPanoToAll = () => mutate((n) => {
    if (!n.panorama) return;
    const cur = (n.panorama.viewports || [])[activeSlide] || { ox: 50, oy: 50, scale: 1 };
    n.panorama.viewports = n.slides.map(() => ({ ...cur }));
  });

  /* --- Image upload + drag-drop --- */
  const insertImageFile = (file, position) => new Promise((resolve, reject) => {
    if (!file || !file.type?.startsWith("image/")) { toast.error("Please pick an image file"); reject(new Error("not_image")); return; }
    if (file.size > 15 * 1024 * 1024) { toast.error("Image too large (max ~15 MB)"); reject(new Error("too_large")); return; }
    const reader = new FileReader();
    reader.onload = () => {
      const dataUrl = String(reader.result || "");
      const x = position?.x ?? 300;
      const y = position?.y ?? 400;
      const probe = new window.Image();
      probe.onload = () => {
        const scale = probe.width > 720 ? 720 / probe.width : 1;
        addElement({ type: "image", src: dataUrl, x, y, w: Math.round(probe.width * scale), h: Math.round(probe.height * scale), fit: "cover", radius: 24 });
        toast.success("Image added");
        resolve();
      };
      probe.onerror = () => {
        addElement({ type: "image", src: dataUrl, x, y, w: 480, h: 480, fit: "cover", radius: 24 });
        resolve();
      };
      probe.src = dataUrl;
    };
    reader.onerror = () => { toast.error("Failed to read file"); reject(new Error("read_failed")); };
    reader.readAsDataURL(file);
  });
  const onImageFilesSelected = async (files) => {
    for (const f of Array.from(files || [])) { try { await insertImageFile(f); } catch { /* skip */ } }
  };
  const onCanvasDragOver = (e) => { if (e.dataTransfer?.types?.includes("Files")) { e.preventDefault(); setDropHint(true); } };
  const onCanvasDragLeave = () => setDropHint(false);
  const onCanvasDrop = async (e) => {
    e.preventDefault();
    setDropHint(false);
    const files = Array.from(e.dataTransfer?.files || []).filter((f) => f.type.startsWith("image/"));
    if (!files.length) return;
    const rect = canvasRef.current?.getBoundingClientRect();
    let px = 200, py = 200;
    if (rect) {
      px = Math.round((e.clientX - rect.left) / zoom) - 200;
      py = Math.round((e.clientY - rect.top) / zoom) - 200;
      px = Math.max(0, Math.min(CANVAS.w - 400, px));
      py = Math.max(0, Math.min(CANVAS.h - 400, py));
    }
    for (const f of files) { try { await insertImageFile(f, { x: px, y: py }); px += 40; py += 40; } catch { /* skip */ } }
  };

  /* --- Pointer drag: move selected element(s) ---
   * Shift-click toggles an element in/out of the multi-selection (and never
   * starts a drag, matching Figma). Clicking a plain (non-shift) element that's
   * already part of a multi-selection keeps the whole group selected so it can
   * be dragged together; clicking a non-selected element replaces the
   * selection with just that one, as usual. */
  const onPointerDown = useCallback((e, el) => {
    e.stopPropagation();
    if (el.locked) return;
    if (e.shiftKey) {
      setSelectedIds((prev) => {
        const next = new Set(prev);
        if (next.has(el.id)) next.delete(el.id); else next.add(el.id);
        return next;
      });
      setSelectedId(el.id);
      return;
    }
    const prevIds = selectedIdsRef.current;
    const ids = (prevIds.has(el.id) && prevIds.size > 1) ? prevIds : new Set([el.id]);
    if (ids !== prevIds) selectSingle(el.id);
    else setSelectedId(el.id);
    const slideNow = projRef.current?.slides?.[activeSlideRef.current];
    if (!slideNow) return;
    beginGesture();
    const starts = {};
    slideNow.elements.forEach((e2) => { if (ids.has(e2.id)) starts[e2.id] = { x: e2.x, y: e2.y }; });
    // Snapping only applies to a single-element drag; the "others" it aligns to
    // are every element that isn't being dragged.
    const single = ids.size === 1 ? el : null;
    const others = single ? slideNow.elements.filter((e2) => e2.id !== el.id) : [];
    dragState.current = { ids, starts, startX: e.clientX, startY: e.clientY, scale: zoomRef.current, single, others };
    window.addEventListener("pointermove", onPointerMove);
    window.addEventListener("pointerup", onPointerUp);
  }, [beginGesture, selectSingle]); // eslint-disable-line react-hooks/exhaustive-deps
  const onPointerMove = useCallback((e) => {
    const ds = dragState.current;
    if (!ds) return;
    const dx = (e.clientX - ds.startX) / ds.scale;
    const dy = (e.clientY - ds.startY) / ds.scale;
    if (ds.single) {
      const start = ds.starts[ds.single.id];
      const snap = computeSnap(ds.single, start.x + dx, start.y + dy, ds.others);
      patchElement(ds.single.id, { x: snap.x, y: snap.y });
      setGuides(snap.guides);
      setInteraction({ mode: "drag", label: `${snap.x}, ${snap.y}` });
      return;
    }
    ds.ids.forEach((id) => {
      const start = ds.starts[id];
      if (!start) return;
      patchElement(id, { x: Math.round(start.x + dx), y: Math.round(start.y + dy) });
    });
    setInteraction({ mode: "drag", label: `${dx >= 0 ? "+" : ""}${Math.round(dx)}, ${dy >= 0 ? "+" : ""}${Math.round(dy)}` });
  }, [patchElement]);
  const onPointerUp = useCallback(() => {
    dragState.current = null;
    setGuides([]);
    setInteraction(null);
    endGesture();
    window.removeEventListener("pointermove", onPointerMove);
    window.removeEventListener("pointerup", onPointerUp);
  }, [endGesture]); // eslint-disable-line react-hooks/exhaustive-deps

  /* --- Marquee select: drag on empty canvas to box-select elements --- */
  const onCanvasBgPointerDown = useCallback((e) => {
    if (e.target !== e.currentTarget || !canvasRef.current) return;
    const rect = canvasRef.current.getBoundingClientRect();
    const startX = (e.clientX - rect.left) / zoomRef.current;
    const startY = (e.clientY - rect.top) / zoomRef.current;
    if (!e.shiftKey) selectSingle(null);
    marqueeState.current = { startX, startY, x: startX, y: startY, w: 0, h: 0, shift: e.shiftKey };
    setMarqueeRect({ x: startX, y: startY, w: 0, h: 0 });
    window.addEventListener("pointermove", onMarqueeMove);
    window.addEventListener("pointerup", onMarqueeUp);
  }, [selectSingle]); // eslint-disable-line react-hooks/exhaustive-deps
  const onMarqueeMove = useCallback((e) => {
    const ms = marqueeState.current;
    if (!ms || !canvasRef.current) return;
    const rect = canvasRef.current.getBoundingClientRect();
    const curX = (e.clientX - rect.left) / zoomRef.current;
    const curY = (e.clientY - rect.top) / zoomRef.current;
    const x = Math.min(ms.startX, curX), y = Math.min(ms.startY, curY);
    const w = Math.abs(curX - ms.startX), h = Math.abs(curY - ms.startY);
    ms.x = x; ms.y = y; ms.w = w; ms.h = h;
    setMarqueeRect({ x, y, w, h });
  }, []);
  const onMarqueeUp = useCallback(() => {
    const ms = marqueeState.current;
    marqueeState.current = null;
    setMarqueeRect(null);
    window.removeEventListener("pointermove", onMarqueeMove);
    window.removeEventListener("pointerup", onMarqueeUp);
    if (!ms || (ms.w < 4 && ms.h < 4) || !slide) return;
    const hit = new Set();
    slide.elements.forEach((el2) => {
      const overlap = el2.x < ms.x + ms.w && el2.x + el2.w > ms.x && el2.y < ms.y + ms.h && el2.y + el2.h > ms.y;
      if (overlap) hit.add(el2.id);
    });
    if (!hit.size) return;
    setSelectedIds((prev) => {
      const next = ms.shift ? new Set(prev) : new Set();
      hit.forEach((id) => next.add(id));
      return next;
    });
    setSelectedId([...hit][0]);
  }, [slide]); // eslint-disable-line react-hooks/exhaustive-deps

  /* --- Resize handles (8-directional) --- */
  const onResizeStart = useCallback((e, el, pos) => {
    e.stopPropagation();
    selectSingle(el.id);
    beginGesture();
    resizeState.current = {
      id: el.id, pos,
      startX: e.clientX, startY: e.clientY,
      ox: el.x, oy: el.y, ow: el.w, oh: el.h,
      keepAspect: el.type === "image" || el.type === "icon",
      scale: zoomRef.current,
    };
    window.addEventListener("pointermove", onResizeMove);
    window.addEventListener("pointerup", onResizeEnd);
  }, [beginGesture, selectSingle]); // eslint-disable-line react-hooks/exhaustive-deps
  const onResizeMove = useCallback((e) => {
    const rs = resizeState.current;
    if (!rs) return;
    const dx = (e.clientX - rs.startX) / rs.scale;
    const dy = (e.clientY - rs.startY) / rs.scale;
    let { ox, oy, ow, oh } = rs;
    let nx = ox, ny = oy, nw = ow, nh = oh;
    const min = 24;
    // Handle position → dimension deltas
    if (rs.pos.includes("e")) nw = Math.max(min, ow + dx);
    if (rs.pos.includes("s")) nh = Math.max(min, oh + dy);
    if (rs.pos.includes("w")) { nw = Math.max(min, ow - dx); nx = ox + (ow - nw); }
    if (rs.pos.includes("n")) { nh = Math.max(min, oh - dy); ny = oy + (oh - nh); }
    if (rs.keepAspect && rs.pos.length === 2) {
      const aspect = ow / oh;
      // choose the dominant axis change
      if (Math.abs(dx) > Math.abs(dy)) nh = nw / aspect;
      else nw = nh * aspect;
      // reapply anchor for w/n handles
      if (rs.pos.includes("w")) nx = ox + (ow - nw);
      if (rs.pos.includes("n")) ny = oy + (oh - nh);
    }
    patchElement(rs.id, {
      x: Math.round(nx), y: Math.round(ny),
      w: Math.round(nw), h: Math.round(nh),
    });
    setInteraction({ mode: "resize", label: `${Math.round(nw)} × ${Math.round(nh)}` });
  }, [patchElement]);
  const onResizeEnd = useCallback(() => {
    resizeState.current = null;
    setInteraction(null);
    endGesture();
    window.removeEventListener("pointermove", onResizeMove);
    window.removeEventListener("pointerup", onResizeEnd);
  }, [endGesture]); // eslint-disable-line react-hooks/exhaustive-deps

  /* --- Rotation handle (on-canvas, Figma-style) ---
   * Drags around the element's center; snaps to the eight 45° stops within 3°
   * unless Shift is held (free rotation). The HUD shows the live angle. */
  const onRotateMove = useCallback((e) => {
    const rs = rotateState.current;
    if (!rs) return;
    const pointerDeg = Math.atan2(e.clientY - rs.cy, e.clientX - rs.cx) * 180 / Math.PI;
    let next = rs.startRotate + (pointerDeg - rs.startPointerDeg);
    next = ((next + 180) % 360 + 360) % 360 - 180; // normalize to (-180, 180]
    if (!e.shiftKey) {
      for (const s of [-180, -135, -90, -45, 0, 45, 90, 135, 180]) {
        if (Math.abs(next - s) <= 3) { next = s; break; }
      }
    }
    next = Math.round(next);
    if (next === 180) next = -180;
    patchElement(rs.id, { rotate: next === 0 ? 0 : next });
    setInteraction({ mode: "rotate", label: `${next}°` });
  }, [patchElement]);
  const onRotateEnd = useCallback(() => {
    rotateState.current = null;
    setInteraction(null);
    endGesture();
    window.removeEventListener("pointermove", onRotateMove);
    window.removeEventListener("pointerup", onRotateEnd);
  }, [endGesture]); // eslint-disable-line react-hooks/exhaustive-deps
  const onRotateStart = useCallback((e, el) => {
    e.stopPropagation();
    if (!canvasRef.current) return;
    selectSingle(el.id);
    beginGesture();
    const rect = canvasRef.current.getBoundingClientRect();
    const zoomNow = zoomRef.current;
    const b = elementBounds(el, measuredRef.current);
    const cx = rect.left + (b.x + b.w / 2) * zoomNow;
    const cy = rect.top + (b.y + b.h / 2) * zoomNow;
    rotateState.current = {
      id: el.id, cx, cy,
      startPointerDeg: Math.atan2(e.clientY - cy, e.clientX - cx) * 180 / Math.PI,
      startRotate: el.rotate || 0,
    };
    window.addEventListener("pointermove", onRotateMove);
    window.addEventListener("pointerup", onRotateEnd);
  }, [beginGesture, selectSingle]); // eslint-disable-line react-hooks/exhaustive-deps

  /* --- Group resize: uniform scale of a multi-selection from a corner of its
   * union bbox — positions, sizes, and text/badge font sizes all scale
   * together, anchored at the opposite corner (Canva behavior). --- */
  const onGroupResizeMove = useCallback((e) => {
    const gs = groupResizeState.current;
    if (!gs) return;
    const dx = (e.clientX - gs.startX) / gs.scale;
    const dy = (e.clientY - gs.startY) / gs.scale;
    const dirX = gs.pos.includes("e") ? 1 : -1;
    const dirY = gs.pos.includes("s") ? 1 : -1;
    const sW = (gs.bw + dirX * dx) / gs.bw;
    const sH = (gs.bh + dirY * dy) / gs.bh;
    // Dominant axis, normalized by bbox aspect so diagonal drags feel 1:1.
    let s = Math.abs(dx) * gs.bh > Math.abs(dy) * gs.bw ? sW : sH;
    s = Math.max(0.05, s);
    gs.members.forEach((m) => {
      const patch = {
        x: Math.round(gs.ax + (m.x - gs.ax) * s),
        y: Math.round(gs.ay + (m.y - gs.ay) * s),
        w: Math.max(2, Math.round(m.w * s)),
        h: Math.max(2, Math.round(m.h * s)),
      };
      if (m.size) patch.size = Math.max(6, Math.round(m.size * s));
      patchElement(m.id, patch);
    });
    setInteraction({ mode: "resize", label: `${Math.round(gs.bw * s)} × ${Math.round(gs.bh * s)}` });
  }, [patchElement]);
  const onGroupResizeEnd = useCallback(() => {
    groupResizeState.current = null;
    setInteraction(null);
    endGesture();
    window.removeEventListener("pointermove", onGroupResizeMove);
    window.removeEventListener("pointerup", onGroupResizeEnd);
  }, [endGesture]); // eslint-disable-line react-hooks/exhaustive-deps
  const onGroupResizeStart = useCallback((e, pos) => {
    e.stopPropagation();
    const slideNow = projRef.current?.slides?.[activeSlideRef.current];
    const ids = selectedIdsRef.current;
    if (!slideNow || ids.size < 2) return;
    const els = slideNow.elements.filter((el) => ids.has(el.id) && !el.locked);
    if (!els.length) return;
    beginGesture();
    const bs = els.map((el) => elementBounds(el, measuredRef.current));
    const minX = Math.min(...bs.map((b) => b.x)), minY = Math.min(...bs.map((b) => b.y));
    const maxX = Math.max(...bs.map((b) => b.x + b.w)), maxY = Math.max(...bs.map((b) => b.y + b.h));
    groupResizeState.current = {
      pos, startX: e.clientX, startY: e.clientY, scale: zoomRef.current,
      bw: Math.max(1, maxX - minX), bh: Math.max(1, maxY - minY),
      // Anchor = the corner opposite the handle being dragged.
      ax: pos.includes("w") ? maxX : minX,
      ay: pos.includes("n") ? maxY : minY,
      members: els.map((el, i) => ({ id: el.id, x: el.x, y: el.y, w: bs[i].w, h: bs[i].h, size: el.size })),
    };
    window.addEventListener("pointermove", onGroupResizeMove);
    window.addEventListener("pointerup", onGroupResizeEnd);
  }, [beginGesture]); // eslint-disable-line react-hooks/exhaustive-deps

  /* --- Panorama direct-drag overlay (manual mode) --- */
  const panoManual = proj?.panorama?.mode === "manual" && proj?.panorama?.src && !selected;
  const onPanoDragStart = (e) => {
    e.stopPropagation();
    beginGesture();
    const vp = (proj.panorama.viewports || [])[activeSlide] || { ox: 50, oy: 50, scale: 1 };
    panoDragState.current = { startX: e.clientX, startY: e.clientY, ox: vp.ox ?? 50, oy: vp.oy ?? 50, scale: vp.scale ?? 1 };
    window.addEventListener("pointermove", onPanoDragMove);
    window.addEventListener("pointerup", onPanoDragEnd);
  };
  const onPanoDragMove = (e) => {
    const ds = panoDragState.current;
    if (!ds) return;
    // Convert pixel drag to percentage — full pan = ~1 canvas width.
    const dxPct = ((e.clientX - ds.startX) / (CANVAS.w * zoom)) * -100;
    const dyPct = ((e.clientY - ds.startY) / (CANVAS.h * zoom)) * -100;
    const nextOx = Math.max(0, Math.min(100, ds.ox + dxPct));
    const nextOy = Math.max(0, Math.min(100, ds.oy + dyPct));
    setPanoViewport({ ox: nextOx, oy: nextOy, scale: ds.scale });
  };
  const onPanoDragEnd = () => {
    panoDragState.current = null;
    endGesture();
    window.removeEventListener("pointermove", onPanoDragMove);
    window.removeEventListener("pointerup", onPanoDragEnd);
  };
  const onPanoWheel = (e) => {
    if (!panoManual) return;
    e.preventDefault();
    // Wheel has no discrete start/end event — beginGesture()'s own idle
    // timeout re-arms on every tick, so a burst of wheel events is treated
    // as one gesture that ends shortly after the last tick.
    beginGesture();
    const vp = (proj.panorama.viewports || [])[activeSlide] || { ox: 50, oy: 50, scale: 1 };
    const nextScale = Math.max(1, Math.min(3, (vp.scale ?? 1) + (e.deltaY < 0 ? 0.1 : -0.1)));
    setPanoViewport({ ...vp, scale: nextScale });
  };

  /* --- Keyboard shortcuts --- */
  useEffect(() => {
    const h = (e) => {
      if (e.target?.tagName === "INPUT" || e.target?.tagName === "TEXTAREA" || e.target?.isContentEditable) return;
      const meta = e.ctrlKey || e.metaKey;
      if (meta && !e.shiftKey && (e.key === "z" || e.key === "Z")) { e.preventDefault(); undo(); return; }
      if (meta && ((e.shiftKey && (e.key === "z" || e.key === "Z")) || e.key === "y")) { e.preventDefault(); redo(); return; }
      // Copy selected element to internal clipboard.
      if (meta && (e.key === "c" || e.key === "C") && selectedId) {
        const el = slide?.elements?.find((x) => x.id === selectedId);
        if (el) {
          clipboardRef.current = JSON.parse(JSON.stringify(el));
          toast.success("Copied");
        }
        e.preventDefault();
        return;
      }
      // Paste from internal clipboard.
      if (meta && (e.key === "v" || e.key === "V") && clipboardRef.current) {
        e.preventDefault();
        const src = clipboardRef.current;
        const copy = { ...src, id: newId(), x: (src.x || 0) + 40, y: (src.y || 0) + 40 };
        mutate((n) => n.slides[activeSlide].elements.push(copy));
        selectSingle(copy.id);
        toast.success("Pasted");
        return;
      }
      // Duplicate selected in-place.
      if (meta && (e.key === "d" || e.key === "D") && selectedId) {
        e.preventDefault();
        duplicateElement(selectedId);
        return;
      }
      if (!selectedId && selectedIds.size === 0) return;
      if (e.key === "Backspace" || e.key === "Delete") { e.preventDefault(); deleteSelectedElements(); return; }
      // Arrow-key nudge: 1px, or 10px with shift held.
      const step = e.shiftKey ? 10 : 1;
      if (e.key === "ArrowLeft") { e.preventDefault(); nudgeSelected(-step, 0); }
      else if (e.key === "ArrowRight") { e.preventDefault(); nudgeSelected(step, 0); }
      else if (e.key === "ArrowUp") { e.preventDefault(); nudgeSelected(0, -step); }
      else if (e.key === "ArrowDown") { e.preventDefault(); nudgeSelected(0, step); }
    };
    window.addEventListener("keydown", h);
    return () => window.removeEventListener("keydown", h);
  }, [selectedId, selectedIds, undo, redo, slide, activeSlide, mutate]); // eslint-disable-line react-hooks/exhaustive-deps

  /* --- Insert your own headshot as an element on the current slide. --- */
  const insertHeadshot = () => {
    if (!user?.avatar_url) {
      toast.error("Upload your headshot in Settings → Profile first");
      return;
    }
    addElement({
      type: "image", role: "headshot", src: user.avatar_url,
      x: 720, y: CANVAS.h - 340,
      w: 260, h: 260,
      fit: "cover", radius: 999,
    });
  };

  /** Headshot + name + handle, added to every slide that doesn't already
   * have one (same idempotency pattern as the brand-kit logo apply below). */
  const insertAuthorBar = () => {
    if (!user?.avatar_url) {
      toast.error("Upload your headshot in Settings → Profile first");
      return;
    }
    mutate((n) => {
      for (const s of n.slides) {
        const has = (s.elements || []).some((e) => e.role === "author_name");
        if (has) continue;
        s.elements.push(
          { id: newId(), type: "image", role: "headshot", src: user.avatar_url, x: 80, y: CANVAS.h - 200, w: 120, h: 120, fit: "cover", radius: 999 },
          { id: newId(), type: "text", role: "author_name", text: user.name || "", x: 216, y: CANVAS.h - 196, w: 600, h: 50, font: "Inter", size: 32, weight: 700, color: "text", align: "left" },
          { id: newId(), type: "text", role: "author_handle", text: user.headline || "", x: 216, y: CANVAS.h - 146, w: 600, h: 40, font: "Inter", size: 22, weight: 400, color: "muted", align: "left" },
        );
      }
    });
    toast.success("Author bar added to every slide");
  };

  /* --- Deck-wide chrome toggles (slide numbers / progress dots / swipe hint) --- */
  const setDeckSetting = useCallback((key, value) => {
    mutate((n) => { n[key] = value; });
  }, [mutate]);

  /* --- Save / export --- */
  const save = async () => {
    setBusy(true);
    try {
      const clean = stripLocalKeys(proj);
      await api.put(`/carousel/${id}`, {
        slides: clean.slides, brand: proj.brand, platform: proj.platform,
        topic: proj.topic, palette_id: proj.palette_id, panorama: proj.panorama || null,
        show_slide_numbers: !!proj.show_slide_numbers,
        show_progress_dots: !!proj.show_progress_dots,
        show_swipe_hint: !!proj.show_swipe_hint,
        show_branding: !!proj.show_branding,
      });
      toast.success("Saved");
    } catch { toast.error("Save failed"); }
    finally { setBusy(false); }
  };

  const renderSlideToDataUrl = (slideIdx, scale = 2) => new Promise((resolve, reject) => {
    // Live-render the slide off-screen via React, then rasterise with html2canvas.
    const host = document.createElement("div");
    host.style.cssText = [
      "position:fixed", "left:-99999px", "top:0",
      `width:${CANVAS.w}px`, `height:${CANVAS.h}px`,
      `background:${renderBackground(proj.slides[slideIdx].bg, palette)}`,
      "overflow:hidden", "pointer-events:none",
    ].join(";");
    document.body.appendChild(host);
    const root = createRoot(host);
    const cleanup = () => {
      try { root.unmount(); } catch { /* ignore */ }
      try { host.remove(); } catch { /* ignore */ }
    };
    (async () => {
      try {
        root.render(
          <>
            <PanoramaLayer panorama={proj.panorama} slideIdx={slideIdx} totalSlides={proj.slides.length} />
            {proj.slides[slideIdx].elements.map((el) => (
              <ElementRender key={el.id} el={el} palette={palette} onPointerDown={() => {}} />
            ))}
            <DeckOverlay proj={proj} slideIdx={slideIdx} palette={palette} />
          </>
        );
        await new Promise((r) => setTimeout(r, 150));
        const imgs = host.querySelectorAll("img");
        await Promise.all(Array.from(imgs).map((img) => new Promise((res) => {
          if (img.complete && img.naturalWidth) return res();
          img.onload = () => res();
          img.onerror = () => res();
          setTimeout(res, 3000);
        })));
        const canvas = await html2canvas(host, {
          width: CANVAS.w, height: CANVAS.h,
          windowWidth: CANVAS.w, windowHeight: CANVAS.h,
          scale, useCORS: true, allowTaint: true, backgroundColor: null, logging: false,
        });
        const dataUrl = canvas.toDataURL("image/png", 0.92);
        cleanup(); resolve(dataUrl);
      } catch (err) {
        cleanup();
        console.error("[creq] slide", slideIdx, "render failed:", err);
        reject(err instanceof Error ? err : new Error(String(err?.message || err || "render_failed")));
      }
    })();
  });

  const exportSlidePng = async () => {
    setBusy(true);
    try {
      // A saved deck can use fonts beyond the 10 preloaded at app start; make
      // sure they're actually fetched before html2canvas rasterizes, or it
      // silently falls back to a system font for that text.
      await waitForProjectFonts(proj.slides);
      const dataUrl = await renderSlideToDataUrl(activeSlide);
      const a = document.createElement("a");
      a.href = dataUrl;
      a.download = `${(proj.topic || "slide").slice(0, 40).replace(/\W+/g, "-")}-${activeSlide + 1}.png`;
      a.click();
      toast.success("PNG exported");
    } catch { toast.error("PNG export failed"); }
    finally { setBusy(false); }
  };

  const [exportProgress, setExportProgress] = useState(null);

  const exportPdfSlides = async (indices, qualityId = "standard") => {
    if (!proj?.slides?.length) return;
    const chosen = (indices?.length ? indices : proj.slides.map((_, i) => i))
      .filter((i) => i >= 0 && i < proj.slides.length)
      .sort((a, b) => a - b);
    if (!chosen.length) { toast.error("Pick at least one slide"); return; }
    const scale = EXPORT_QUALITIES.find((q) => q.id === qualityId)?.scale ?? 2;
    setBusy(true);
    setExportProgress({ done: 0, total: chosen.length });
    try {
      await waitForProjectFonts(proj.slides);
      const pdf = new jsPDF({
        orientation: CANVAS.h > CANVAS.w ? "portrait" : "landscape",
        unit: "px", format: [CANVAS.w, CANVAS.h], compress: true,
      });
      for (let k = 0; k < chosen.length; k++) {
        const dataUrl = await renderSlideToDataUrl(chosen[k], scale);
        if (k > 0) pdf.addPage([CANVAS.w, CANVAS.h], CANVAS.h > CANVAS.w ? "portrait" : "landscape");
        pdf.addImage(dataUrl, "PNG", 0, 0, CANVAS.w, CANVAS.h);
        // A silent multi-second wait reads as broken even when it isn't —
        // this is most of the fix for "export feels slow."
        setExportProgress({ done: k + 1, total: chosen.length });
      }
      pdf.save(`${(proj.topic || "carousel").slice(0, 40).replace(/\W+/g, "-")}-${chosen.length}-slides.pdf`);
      toast.success(`Exported ${chosen.length}-page PDF`);
    } catch (err) {
      console.error(err);
      toast.error("PDF export failed");
    } finally { setBusy(false); setExportProgress(null); }
  };

  /* --- Brand kit apply / AI copy assist --- */
  const applyBrandKit = async (kit) => {
    if (!kit) return;
    mutate((n) => {
      if (kit.palette_id) n.palette_id = kit.palette_id;
      n.brand = { ...(n.brand || {}), logo_url: kit.logo_url, colors: kit.colors, fonts: kit.fonts };
      if (kit.logo_url) {
        for (const s of n.slides) {
          const hasLogo = (s.elements || []).some((e) => e.type === "image" && e.role === "logo");
          if (!hasLogo) {
            s.elements.push({ id: newId(), type: "image", role: "logo", src: kit.logo_url, x: 80, y: CANVAS.h - 160, w: 160, h: 80, fit: "contain" });
          }
        }
      }
    });
    toast.success(`Applied brand kit "${kit.name}"`);
  };

  const aiAssistText = async (mode) => {
    if (!selected || selected.type !== "text" || !proj) return;
    setBusy(true);
    try {
      const instructionMap = {
        punchier: "Rewrite this text to be punchier and more direct. Same intent, half the words if possible.",
        shorter: "Rewrite this text at half the length while preserving the core idea.",
        catchier: "Rewrite this as a scroll-stopping hook for a LinkedIn / Instagram carousel.",
        formal: "Rewrite this in a formal, executive tone.",
      };
      const { data } = await api.post("/carousel/edit", {
        project_id: id, slide_index: activeSlide,
        instruction: `Rewrite ONLY the title field of the slide. ${instructionMap[mode]} Current text: "${selected.text}"`,
      });
      if (data?.slide?.title) {
        patchElement(selected.id, { text: data.slide.title });
        toast.success("Rewritten by AI");
      } else {
        toast.error("No rewrite returned");
      }
    } catch (err) { if (!isCreditError(err)) toast.error("AI assist failed"); }
    finally { setBusy(false); }
  };

  /** Draft a fresh batch of slides for a topic and append them to the deck —
   * the in-editor counterpart to the Projects-page wizard, for decks that
   * already exist and just need more (or their first real) content. */
  const generateContentForTopic = async (topic, slideCount) => {
    setBusy(true);
    try {
      const { data } = await api.post("/carousel/generate", {
        topic: topic.trim(), platform: proj.platform || "linkedin", slide_count: slideCount, tone: "confident, punchy",
      });
      const newSlides = (data.slides || []).map(legacySlideToElements);
      if (!newSlides.length) { toast.error("No slides generated"); return; }
      mutate((n) => { n.slides.push(...newSlides); });
      setActiveSlide(proj.slides.length);
      setShowGenerateContent(false);
      toast.success(`Added ${newSlides.length} AI-generated slide${newSlides.length === 1 ? "" : "s"}`);
    } catch (err) { if (!isCreditError(err)) toast.error("Generation failed — try again"); }
    finally { setBusy(false); }
  };

  if (!proj) return <div className="p-6 sm:p-8 text-neutral-400">Loading…</div>;

  return (
    <div>
      <PageHeader
        title={proj.topic}
        subtitle={`${proj.slides.length} slide${proj.slides.length === 1 ? "" : "s"} · ${palette.name} palette`}
        right={
          <div className="flex flex-wrap gap-2">
            <button onClick={() => nav("/app/create-eq")} className="btn-ghost"><ChevronLeft size={14} /> Projects</button>
            <button onClick={undo} title="Undo (Ctrl+Z)" data-testid="undo-btn" className="btn-ghost"><Undo2 size={14} /></button>
            <button onClick={redo} title="Redo (Ctrl+Shift+Z)" data-testid="redo-btn" className="btn-ghost"><Redo2 size={14} /></button>
            <button onClick={() => setViewMode(viewMode === "focus" ? "board" : "focus")} data-testid="view-mode-toggle" className="btn-ghost">
              {viewMode === "focus" ? <><LayoutGrid size={14} /> Board</> : <><Maximize2 size={14} /> Focus</>}
            </button>
            <button onClick={() => setShowGenerateContent(true)} data-testid="generate-content-open" className="btn-secondary"><Wand2 size={14} /> Generate content</button>
            <button onClick={() => setShowPanorama(true)} data-testid="panorama-open" className="btn-secondary"><Mountain size={14} /> Panorama</button>
            <button onClick={() => setShowAiImage(true)} data-testid="ai-image-open" className="btn-secondary"><Wand2 size={14} /> AI Image</button>
            <button onClick={() => setShowBrandKit(true)} data-testid="brand-kit-open" className="btn-secondary"><Sparkles size={14} /> Brand kit</button>
            <button onClick={exportSlidePng} data-testid="export-png-btn" className="btn-secondary"><Download size={14} /> PNG</button>
            <button onClick={() => setShowPdfPicker(true)} disabled={busy} data-testid="export-pdf-btn" className="btn-secondary"><FileText size={14} /> PDF</button>
            <button onClick={save} disabled={busy} data-testid="save-carousel-btn" className="btn-primary">
              {busy ? <><Loader2 size={14} className="animate-spin" /> Saving…</> : <><Save size={14} /> Save</>}
            </button>
          </div>
        }
      />

      {viewMode === "focus" ? (
        <div className="grid grid-cols-12 min-h-[calc(100vh-90px)] bg-neutral-100 overflow-x-auto">
          <aside className="col-span-2 border-r border-line bg-white overflow-y-auto">
            <LeftPanel
              onTemplate={(tpl) => applyTemplateToSlide(tpl)}
              onAddText={(preset) => addElement(preset)}
              onAddShape={(shape) => addElement({ type: "shape", shape, x: 400, y: 500, w: 280, h: 280, fill: "accent", opacity: 1, radius: shape === "circle" ? 999 : 24 })}
              onAddLine={() => addElement({ type: "line", x: 80, y: 700, w: 920, h: 4, color: "text" })}
              onAddBadge={() => addElement({ type: "badge", x: 80, y: 96, text: "NEW", bg: "accent", color: "bg", radius: 999, size: 20 })}
              onAddIcon={(name) => addElement({ type: "icon", x: 400, y: 500, w: 128, name, color: "accent", stroke: 2 })}
              onAddImage={() => imageFileRef.current?.click()}
              onAddImageUrl={() => {
                const url = prompt("Paste image URL (PNG/JPG/SVG)");
                if (url && url.trim()) addElement({ type: "image", src: url.trim(), x: 300, y: 400, w: 480, h: 480, fit: "cover", radius: 24 });
              }}
              onAddHeadshot={insertHeadshot}
              onAddAuthorBar={insertAuthorBar}
              hasHeadshot={!!user?.avatar_url}
            />
          </aside>

          <section className="col-span-7 relative overflow-auto"
            onDragOver={onCanvasDragOver} onDragLeave={onCanvasDragLeave} onDrop={onCanvasDrop}>
            {dropHint && (
              <div className="absolute inset-0 z-10 flex items-center justify-center pointer-events-none">
                <div className="bg-ink text-white px-4 py-2 rounded-full font-mono text-xs uppercase tracking-widest">Drop image to add</div>
              </div>
            )}
              <div className="p-4 sm:p-6 flex items-start justify-center">
              <div className="relative" style={{ width: CANVAS.w * zoom, height: CANVAS.h * zoom }}>
                <div
                  ref={canvasRef}
                  onPointerDown={onCanvasBgPointerDown}
                  className={`absolute inset-0 origin-top-left overflow-hidden shadow-[0_20px_80px_-30px_rgba(0,0,0,0.35)] rounded-md creq-canvas ${interaction || marqueeRect ? "creq-interacting" : ""} ${interaction?.mode === "drag" ? "creq-dragging" : ""} ${marqueeRect ? "creq-marqueeing" : ""} ${dropHint ? "ring-2 ring-ink" : ""}`}
                  style={{ width: CANVAS.w, height: CANVAS.h, transform: `scale(${zoom})`, transformOrigin: "top left", background: renderBackground(slide.bg, palette), "--inv-zoom": 1 / zoom }}
                >
                  <PanoramaLayer panorama={proj.panorama} slideIdx={activeSlide} totalSlides={proj.slides.length} />
                  {panoManual && (
                    <div
                      onPointerDown={onPanoDragStart}
                      onWheel={onPanoWheel}
                      data-testid="pano-drag-overlay"
                      style={{ position: "absolute", inset: 0, cursor: "grab", background: "transparent", zIndex: 1 }}
                      title="Drag to pan · scroll to zoom"
                    />
                  )}
                  {slide.elements.map((el) => (
                    <ElementRender key={el.id} el={el} palette={palette}
                      onPointerDown={onPointerDown}
                      onMeasure={onElementMeasure} />
                  ))}
                  <DeckOverlay proj={proj} slideIdx={activeSlide} palette={palette} />
                  <SelectionChrome
                    els={slide.elements.filter((e2) => selectedIds.has(e2.id))}
                    zoom={zoom}
                    measured={measuredRef.current}
                    interaction={interaction}
                    onResizeStart={onResizeStart}
                    onRotateStart={onRotateStart}
                    onGroupResizeStart={onGroupResizeStart}
                  />
                  {marqueeRect && (
                    <div data-testid="marquee-select" style={{
                      position: "absolute", left: marqueeRect.x, top: marqueeRect.y,
                      width: marqueeRect.w, height: marqueeRect.h,
                      border: `${1 / zoom}px solid #1D1D1F`, background: "rgba(29,29,31,0.06)",
                      pointerEvents: "none", zIndex: 30,
                    }} />
                  )}
                  {guides.map((g, i) => (
                    <div key={i} data-testid="snap-guide" style={{
                      position: "absolute", background: "#FF2D8A", pointerEvents: "none", zIndex: 40,
                      ...(g.o === "v"
                        ? { left: g.pos, top: 0, width: 1.5 / zoom, height: CANVAS.h }
                        : { top: g.pos, left: 0, height: 1.5 / zoom, width: CANVAS.w }),
                    }} />
                  ))}
                  {guides.some((g) => (g.o === "v" && g.pos === CANVAS.w / 2) || (g.o === "h" && g.pos === CANVAS.h / 2)) && (
                    <div style={{ position: "absolute", left: CANVAS.w / 2, top: CANVAS.h / 2, pointerEvents: "none", zIndex: 41 }} data-testid="center-cross">
                      <div style={{ position: "absolute", left: -9 / zoom, top: -1 / zoom, width: 18 / zoom, height: 2 / zoom, background: "#FF2D8A", borderRadius: 999 }} />
                      <div style={{ position: "absolute", left: -1 / zoom, top: -9 / zoom, width: 2 / zoom, height: 18 / zoom, background: "#FF2D8A", borderRadius: 999 }} />
                    </div>
                  )}
                </div>
              </div>
            </div>
            <div className="sticky bottom-0 left-0 right-0 bg-white/90 backdrop-blur border-t border-line px-4 py-2 flex items-center gap-2 text-xs">
              <span className="ui-label">Zoom</span>
              <input type="range" min={0.15} max={0.7} step={0.02} value={zoom} onChange={(e) => setZoom(Number(e.target.value))} data-testid="zoom-slider" className="w-32" />
              <span className="font-mono text-neutral-400">{Math.round(zoom * 100)}%</span>
              <div className="ml-4 flex items-center gap-1 flex-wrap">
                {proj.slides.map((s, i) => (
                  <button key={s._k} onClick={() => { setActiveSlide(i); selectSingle(null); }} data-testid={`slide-thumb-${i}`}
                    className={`px-2.5 py-1 rounded-xl text-xs font-mono ${i === activeSlide ? "bg-ink text-white" : "bg-neutral-100 hover:bg-neutral-200"}`}>
                    {i + 1}
                  </button>
                ))}
                <button onClick={() => addSlide()} data-testid="add-slide" className="btn-ghost text-xs py-1"><Plus size={12} /> Slide</button>
                <button onClick={duplicateSlide} data-testid="dup-slide" className="btn-ghost text-xs py-1"><Copy size={12} /></button>
                <button onClick={deleteSlide} data-testid="del-slide" className="btn-ghost text-xs py-1 text-red-600"><Trash2 size={12} /></button>
              </div>
            </div>
          </section>

          <aside className="col-span-3 border-l border-line bg-white overflow-y-auto">
            <RightPanel
              proj={proj} palette={palette} slide={slide} selected={selected} activeSlide={activeSlide}
              selectedCount={selectedIds.size}
              onAlign={alignSelected}
              onPalette={(pid) => setProj({ ...proj, palette_id: pid })}
              onBg={(bg) => patchSlide({ bg })}
              onEditElement={(patch) => selected && patchElement(selected.id, patch)}
              onDelete={() => selected && deleteElement(selected.id)}
              onDeleteMulti={deleteSelectedElements}
              onDuplicate={() => selected && duplicateElement(selected.id)}
              onFront={() => selected && bringToFront(selected.id)}
              onBack={() => selected && sendToBack(selected.id)}
              onAiAssist={aiAssistText}
              onPanoramaViewport={setPanoViewport}
              onPanoramaResetSlide={resetPanoSlide}
              onPanoramaApplyAll={applyPanoToAll}
              onDeckSetting={setDeckSetting}
              onGestureStart={beginGesture}
              onGestureEnd={endGesture}
            />
          </aside>
        </div>
      ) : (
        <BoardView
          proj={proj} palette={palette}
          onFocus={(i) => { setActiveSlide(i); selectSingle(null); setViewMode("focus"); }}
        />
      )}

      {showBrandKit && (
        <BrandKitDrawer
          onClose={() => setShowBrandKit(false)} kits={brandKits}
          onSaved={(kit) => setBrandKits((k) => [kit, ...k])}
          onUpdated={(kit) => setBrandKits((k) => k.map((x) => x.id === kit.id ? kit : x))}
          onDeleted={(bid) => setBrandKits((k) => k.filter((x) => x.id !== bid))}
          onApply={(kit) => { applyBrandKit(kit); setShowBrandKit(false); }}
        />
      )}

      {showAiImage && (
        <AiImageDrawer
          onClose={() => setShowAiImage(false)}
          onAddAsElement={(dataUrl) => {
            addElement({ type: "image", src: dataUrl, x: 120, y: 240, w: 840, h: 840, fit: "cover", radius: 24 });
            setShowAiImage(false);
            toast.success("Image added to slide");
          }}
          onAddAsBackground={(dataUrl) => {
            mutate((n) => {
              const s = n.slides[activeSlide];
              s.elements = (s.elements || []).filter((el) => !(el.type === "image" && el.role === "background"));
              s.elements.unshift({ id: newId(), type: "image", role: "background", src: dataUrl, x: 0, y: 0, w: CANVAS.w, h: CANVAS.h, fit: "cover", radius: 0 });
            });
            setShowAiImage(false);
            toast.success("Background applied");
          }}
        />
      )}

      {showPanorama && (
        <PanoramaDrawer
          onClose={() => setShowPanorama(false)}
          panorama={proj.panorama} slideCount={proj.slides.length}
          onApply={(pano) => {
            mutate((n) => { n.panorama = pano; });
            setShowPanorama(false);
            toast.success(pano ? "Panorama applied to deck" : "Panorama removed");
          }}
        />
      )}

      {showPdfPicker && (
        <PdfExportDialog
          proj={proj} palette={palette} busy={busy} progress={exportProgress}
          onClose={() => setShowPdfPicker(false)}
          onExport={async (indices, quality) => {
            // Stay open through the render so the progress indicator is
            // actually visible — closing immediately (the old behavior) meant
            // "Rendering slide X of N" could never be seen, since the dialog
            // unmounted before the first slide even started.
            await exportPdfSlides(indices, quality);
            setShowPdfPicker(false);
          }}
        />
      )}

      {showGenerateContent && (
        <GenerateContentDialog
          busy={busy}
          onClose={() => setShowGenerateContent(false)}
          onGenerate={generateContentForTopic}
        />
      )}

      <input
        ref={imageFileRef}
        type="file" accept="image/*" multiple className="hidden"
        data-testid="editor-image-upload"
        onChange={(e) => { onImageFilesSelected(e.target.files); e.target.value = ""; }}
      />
    </div>
  );
}

/** In-editor counterpart to the Projects-page "start with AI" wizard — lets
 * you draft content for a topic straight into the deck you already have
 * open, appending the new slides rather than replacing what's there. */
function GenerateContentDialog({ busy, onClose, onGenerate }) {
  const [topic, setTopic] = useState("");
  const [slideCount, setSlideCount] = useState(3);

  return (
    <div className="fixed inset-0 bg-ink/50 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-white rounded-2xl w-full max-w-lg p-4 sm:p-6" onClick={(e) => e.stopPropagation()} data-testid="generate-content-dialog">
        <h2 className="font-display font-semibold text-2xl mb-1">Generate content</h2>
        <p className="text-sm text-neutral-400 mb-4">Describe a topic — we&apos;ll draft new slides and add them to the end of this deck.</p>
        <textarea
          autoFocus
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          rows={3}
          placeholder='e.g. "Why cold outreach fails in 2026 and how to fix it"'
          data-testid="generate-content-topic"
          className="w-full border border-line rounded-lg px-4 py-3 text-base focus:outline-none focus:border-ink"
        />
        <div className="flex items-center gap-2 mt-3">
          <span className="text-xs text-neutral-400">Slides to add:</span>
          {[1, 3, 5, 6].map((n) => (
            <button key={n} onClick={() => setSlideCount(n)} data-testid={`generate-content-count-${n}`}
              className={`px-3 py-1 rounded-xl text-xs font-mono ${slideCount === n ? "bg-ink text-white" : "bg-neutral-100 hover:bg-neutral-200"}`}>
              {n}
            </button>
          ))}
        </div>
        <div className="flex justify-end gap-2 mt-5">
          <button onClick={onClose} className="btn-ghost">Cancel</button>
          <button onClick={() => onGenerate(topic, slideCount)} disabled={busy || !topic.trim()} data-testid="generate-content-submit"
            className="btn-primary disabled:opacity-60">
            {busy ? <><Loader2 size={14} className="animate-spin" /> Drafting…</> : <><Wand2 size={14} /> Generate</>}
          </button>
        </div>
      </div>
    </div>
  );
}
